version: '3.8'

services:
  postgres-mcp:
    build: .
    network_mode: host
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=light_wash
    stdin_open: true
    tty: true
    volumes:
      - .:/app 